//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class AboutUs
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmAboutUs;
        protected global::System.Web.UI.WebControls.Panel pnlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlLogoArea;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Panel pnlNav;
        protected global::System.Web.UI.WebControls.LinkButton lnkHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkSalon;
        protected global::System.Web.UI.WebControls.LinkButton lnkReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkAboutUs;
        protected global::System.Web.UI.WebControls.Panel pnlUserArea;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.WebControls.Button btnRegister;

        protected global::System.Web.UI.WebControls.Panel pnlAboutHero;
        protected global::System.Web.UI.WebControls.Panel pnlAboutTextCol;
        protected global::System.Web.UI.WebControls.Label lblAboutTitle;
        protected global::System.Web.UI.WebControls.Label lblAboutTagline;
        protected global::System.Web.UI.WebControls.Panel pnlDivider;
        protected global::System.Web.UI.WebControls.Label lblAboutDesc;
        protected global::System.Web.UI.WebControls.Panel pnlAboutImgCol;
        protected global::System.Web.UI.WebControls.Image imgAboutSalon;

        protected global::System.Web.UI.WebControls.Panel pnlWhySection;
        protected global::System.Web.UI.WebControls.Label lblWhyTitle;
        protected global::System.Web.UI.WebControls.Panel pnlFeatureGrid;
        protected global::System.Web.UI.WebControls.Panel pnlCard1;
        protected global::System.Web.UI.WebControls.Panel pnlIcon1;
        protected global::System.Web.UI.WebControls.Label lblIcon1;
        protected global::System.Web.UI.WebControls.Label lblCard1Title;
        protected global::System.Web.UI.WebControls.Label lblCard1Desc;
        protected global::System.Web.UI.WebControls.Panel pnlCard2;
        protected global::System.Web.UI.WebControls.Panel pnlIcon2;
        protected global::System.Web.UI.WebControls.Label lblIcon2;
        protected global::System.Web.UI.WebControls.Label lblCard2Title;
        protected global::System.Web.UI.WebControls.Label lblCard2Desc;
        protected global::System.Web.UI.WebControls.Panel pnlCard3;
        protected global::System.Web.UI.WebControls.Panel pnlIcon3;
        protected global::System.Web.UI.WebControls.Label lblIcon3;
        protected global::System.Web.UI.WebControls.Label lblCard3Title;
        protected global::System.Web.UI.WebControls.Label lblCard3Desc;

        protected global::System.Web.UI.WebControls.Panel pnlFooter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterColumns;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBrandCol;
        protected global::System.Web.UI.WebControls.Panel pnlFooterLogoRow;
        protected global::System.Web.UI.WebControls.Image imgFooterLogo;
        protected global::System.Web.UI.WebControls.Label lblFooterBrand;
        protected global::System.Web.UI.WebControls.Label lblFooterTagline;
        protected global::System.Web.UI.WebControls.Panel pnlFooterQuickLinks;
        protected global::System.Web.UI.WebControls.Label lblQuickLinksTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterSalons;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterAboutUs;
        protected global::System.Web.UI.WebControls.Panel pnlFooterCustomer;
        protected global::System.Web.UI.WebControls.Label lblCustomerTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterMyBooking;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterContact;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSupport;
        protected global::System.Web.UI.WebControls.Label lblSupportTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHelp;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterTerms;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterPrivacy;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterCancellation;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSocial;
        protected global::System.Web.UI.WebControls.Label lblFollowUsTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSocialRow;
        protected global::System.Web.UI.WebControls.HyperLink hlFacebook;
        protected global::System.Web.UI.WebControls.HyperLink hlInstagram;
        protected global::System.Web.UI.WebControls.HyperLink hlTwitter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBottom;
        protected global::System.Web.UI.WebControls.Label lblCopyright;
    }
}
