//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class AdminAddService
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmAdminAddService;
        protected global::System.Web.UI.WebControls.Panel pnlDashboardWrapper;
        protected global::System.Web.UI.WebControls.Panel pnlSidebar;
        protected global::System.Web.UI.WebControls.Panel pnlSidebarLogoBox;
        protected global::System.Web.UI.WebControls.Image imgSidebarLogo;
        protected global::System.Web.UI.WebControls.Panel pnlSidebarNav;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavDashboard;
        protected global::System.Web.UI.WebControls.Image imgNavDashboard;
        protected global::System.Web.UI.WebControls.Label lblTextDashboard;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavUsers;
        protected global::System.Web.UI.WebControls.Image imgNavUsers;
        protected global::System.Web.UI.WebControls.Label lblTextUsers;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavSalons;
        protected global::System.Web.UI.WebControls.Image imgNavSalons;
        protected global::System.Web.UI.WebControls.Label lblTextSalons;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavBookings;
        protected global::System.Web.UI.WebControls.Image imgNavBookings;
        protected global::System.Web.UI.WebControls.Label lblTextBookings;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavServices;
        protected global::System.Web.UI.WebControls.Image imgNavServices;
        protected global::System.Web.UI.WebControls.Label lblTextServices;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavReviews;
        protected global::System.Web.UI.WebControls.Image imgNavReviews;
        protected global::System.Web.UI.WebControls.Label lblTextReviews;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavPayments;
        protected global::System.Web.UI.WebControls.Image imgNavPayments;
        protected global::System.Web.UI.WebControls.Label lblTextPayments;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavSettings;
        protected global::System.Web.UI.WebControls.Image imgNavSettings;
        protected global::System.Web.UI.WebControls.Label lblTextSettings;
        protected global::System.Web.UI.WebControls.Panel pnlSidebarBottom;
        protected global::System.Web.UI.WebControls.LinkButton btnNavLogout;
        protected global::System.Web.UI.WebControls.Image imgNavLogout;
        protected global::System.Web.UI.WebControls.Label lblTextLogout;
        protected global::System.Web.UI.WebControls.Panel pnlMainArea;
        protected global::System.Web.UI.WebControls.Panel pnlTopbar;
        protected global::System.Web.UI.WebControls.Panel pnlSearchWrapper;
        protected global::System.Web.UI.WebControls.Panel pnlSearchIcon;
        protected global::System.Web.UI.WebControls.Image imgSearchIcon;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Panel pnlProfileWidget;
        protected global::System.Web.UI.WebControls.Panel pnlAvatarCircle;
        protected global::System.Web.UI.WebControls.Image imgAdminAvatar;
        protected global::System.Web.UI.WebControls.Panel pnlProfileInfo;
        protected global::System.Web.UI.WebControls.Label lblAdminRole;
        protected global::System.Web.UI.WebControls.Label lblAdminName;
        protected global::System.Web.UI.WebControls.Panel pnlContentArea;
        protected global::System.Web.UI.WebControls.Panel pnlTitleRow;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Label lblPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlFormContainer;
        protected global::System.Web.UI.WebControls.Panel pnlLeftCard;
        protected global::System.Web.UI.WebControls.Panel pnlServiceNameGroup;
        protected global::System.Web.UI.WebControls.Label lblServiceName;
        protected global::System.Web.UI.WebControls.TextBox txtServiceName;
        protected global::System.Web.UI.WebControls.Panel pnlServiceDescGroup;
        protected global::System.Web.UI.WebControls.Label lblServiceDescription;
        protected global::System.Web.UI.WebControls.TextBox txtServiceDescription;
        protected global::System.Web.UI.WebControls.Panel pnlCategoryGroup;
        protected global::System.Web.UI.WebControls.Label lblCategory;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.Panel pnlServicePriceGroup;
        protected global::System.Web.UI.WebControls.Label lblServicePrice;
        protected global::System.Web.UI.WebControls.TextBox txtServicePrice;
        protected global::System.Web.UI.WebControls.Panel pnlRightCard;
        protected global::System.Web.UI.WebControls.Panel pnlServiceImageGroup;
        protected global::System.Web.UI.WebControls.Label lblServiceImage;
        protected global::System.Web.UI.WebControls.Panel pnlUploadBox;
        protected global::System.Web.UI.WebControls.Image imgUploadIcon;
        protected global::System.Web.UI.WebControls.Label lblUploadText;
        protected global::System.Web.UI.WebControls.FileUpload fuServiceImage;
        protected global::System.Web.UI.WebControls.Panel pnlDurationGroup;
        protected global::System.Web.UI.WebControls.Label lblDuration;
        protected global::System.Web.UI.WebControls.DropDownList ddlDuration;
        protected global::System.Web.UI.WebControls.Panel pnlStatusGroup;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Panel pnlActions;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Button btnAddService;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
