//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class AdminAddSalon
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmAdminAddSalon;
        protected global::System.Web.UI.WebControls.Panel pnlDashboardWrapper;
        protected global::System.Web.UI.WebControls.Panel pnlSidebar;
        protected global::System.Web.UI.WebControls.Panel pnlSidebarLogoBox;
        protected global::System.Web.UI.WebControls.Image imgSidebarLogo;
        protected global::System.Web.UI.WebControls.Panel pnlSidebarNav;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavDashboard;
        protected global::System.Web.UI.WebControls.Image imgNavDashboard;
        protected global::System.Web.UI.WebControls.Label lblTextDashboard;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavUsers;
        protected global::System.Web.UI.WebControls.Image imgNavUsers;
        protected global::System.Web.UI.WebControls.Label lblTextUsers;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavSalons;
        protected global::System.Web.UI.WebControls.Image imgNavSalons;
        protected global::System.Web.UI.WebControls.Label lblTextSalons;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavBookings;
        protected global::System.Web.UI.WebControls.Image imgNavBookings;
        protected global::System.Web.UI.WebControls.Label lblTextBookings;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavServices;
        protected global::System.Web.UI.WebControls.Image imgNavServices;
        protected global::System.Web.UI.WebControls.Label lblTextServices;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavReviews;
        protected global::System.Web.UI.WebControls.Image imgNavReviews;
        protected global::System.Web.UI.WebControls.Label lblTextReviews;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavPayments;
        protected global::System.Web.UI.WebControls.Image imgNavPayments;
        protected global::System.Web.UI.WebControls.Label lblTextPayments;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavSettings;
        protected global::System.Web.UI.WebControls.Image imgNavSettings;
        protected global::System.Web.UI.WebControls.Label lblTextSettings;
        protected global::System.Web.UI.WebControls.Panel pnlSidebarBottom;
        protected global::System.Web.UI.WebControls.LinkButton btnNavLogout;
        protected global::System.Web.UI.WebControls.Image imgNavLogout;
        protected global::System.Web.UI.WebControls.Label lblTextLogout;
        protected global::System.Web.UI.WebControls.Panel pnlMainArea;
        protected global::System.Web.UI.WebControls.Panel pnlTopbar;
        protected global::System.Web.UI.WebControls.Panel pnlSearchWrapper;
        protected global::System.Web.UI.WebControls.Panel pnlSearchIcon;
        protected global::System.Web.UI.WebControls.Image imgSearchIcon;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Panel pnlProfileWidget;
        protected global::System.Web.UI.WebControls.Panel pnlAvatarCircle;
        protected global::System.Web.UI.WebControls.Image imgAdminAvatar;
        protected global::System.Web.UI.WebControls.Panel pnlProfileInfo;
        protected global::System.Web.UI.WebControls.Label lblAdminRole;
        protected global::System.Web.UI.WebControls.Label lblAdminName;
        protected global::System.Web.UI.WebControls.Panel pnlContentArea;
        protected global::System.Web.UI.WebControls.Panel pnlTitleRow;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Label lblPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlFormContainer;
        protected global::System.Web.UI.WebControls.Panel pnlLeftCard;
        protected global::System.Web.UI.WebControls.Panel pnlOwnerNameGroup;
        protected global::System.Web.UI.WebControls.Label lblOwnerName;
        protected global::System.Web.UI.WebControls.TextBox txtOwnerName;
        protected global::System.Web.UI.WebControls.Panel pnlPhoneGroup;
        protected global::System.Web.UI.WebControls.Label lblPhoneNumber;
        protected global::System.Web.UI.WebControls.TextBox txtPhoneNumber;
        protected global::System.Web.UI.WebControls.Panel pnlEmailGroup;
        protected global::System.Web.UI.WebControls.Label lblEmailAddress;
        protected global::System.Web.UI.WebControls.TextBox txtEmailAddress;
        protected global::System.Web.UI.WebControls.Panel pnlSalonDetailsGroup;
        protected global::System.Web.UI.WebControls.Label lblSalonDetails;
        protected global::System.Web.UI.WebControls.TextBox txtSalonDetails;
        protected global::System.Web.UI.WebControls.Panel pnlRightCard;
        protected global::System.Web.UI.WebControls.Panel pnlSalonLocationGroup;
        protected global::System.Web.UI.WebControls.Label lblSalonLocation;
        protected global::System.Web.UI.WebControls.TextBox txtSalonLocation;
        protected global::System.Web.UI.WebControls.Panel pnlOpeningHoursGroup;
        protected global::System.Web.UI.WebControls.Label lblOpeningHours;
        protected global::System.Web.UI.WebControls.DropDownList ddlOpeningHours;
        protected global::System.Web.UI.WebControls.Panel pnlSalonImageGroup;
        protected global::System.Web.UI.WebControls.Label lblSalonImage;
        protected global::System.Web.UI.WebControls.Panel pnlUploadBox;
        protected global::System.Web.UI.WebControls.Image imgUploadIcon;
        protected global::System.Web.UI.WebControls.Label lblUploadText;
        protected global::System.Web.UI.WebControls.FileUpload fuSalonImage;
        protected global::System.Web.UI.WebControls.Panel pnlStatusGroup;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Panel pnlActions;
        protected global::System.Web.UI.WebControls.Button btnCancel;
        protected global::System.Web.UI.WebControls.Button btnAddSalon;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
