//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class AdminLogin
    {
        /// <summary>
        /// frmAdminLogin control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm frmAdminLogin;

        /// <summary>
        /// pnlAdminLoginPage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlAdminLoginPage;

        /// <summary>
        /// pnlTopBar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTopBar;

        /// <summary>
        /// pnlLogoBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLogoBox;

        /// <summary>
        /// imgAdminLogo control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAdminLogo;

        /// <summary>
        /// pnlCenterArea control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlCenterArea;

        /// <summary>
        /// pnlLoginCard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlLoginCard;

        /// <summary>
        /// lblLoginHeading control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLoginHeading;

        /// <summary>
        /// pnlEmailGroup control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlEmailGroup;

        /// <summary>
        /// lblEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmail;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// pnlPasswordGroup control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlPasswordGroup;

        /// <summary>
        /// lblPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPassword;

        /// <summary>
        /// txtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// pnlForgotRow control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlForgotRow;

        /// <summary>
        /// lnkForgotPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkForgotPassword;

        /// <summary>
        /// btnLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogin;

        /// <summary>
        /// lblErrorMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorMessage;
    }
}
