//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class AdminDashboard
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmAdminDashboard;
        protected global::System.Web.UI.WebControls.Panel pnlDashboardWrapper;
        protected global::System.Web.UI.WebControls.Panel pnlSidebar;
        protected global::System.Web.UI.WebControls.Panel pnlSidebarLogoBox;
        protected global::System.Web.UI.WebControls.Image imgSidebarLogo;
        protected global::System.Web.UI.WebControls.Panel pnlSidebarNav;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavDashboard;
        protected global::System.Web.UI.WebControls.Image imgNavDashboard;
        protected global::System.Web.UI.WebControls.Label lblTextDashboard;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavUsers;
        protected global::System.Web.UI.WebControls.Image imgNavUsers;
        protected global::System.Web.UI.WebControls.Label lblTextUsers;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavSalons;
        protected global::System.Web.UI.WebControls.Image imgNavSalons;
        protected global::System.Web.UI.WebControls.Label lblTextSalons;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavBookings;
        protected global::System.Web.UI.WebControls.Image imgNavBookings;
        protected global::System.Web.UI.WebControls.Label lblTextBookings;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavServices;
        protected global::System.Web.UI.WebControls.Image imgNavServices;
        protected global::System.Web.UI.WebControls.Label lblTextServices;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavReviews;
        protected global::System.Web.UI.WebControls.Image imgNavReviews;
        protected global::System.Web.UI.WebControls.Label lblTextReviews;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavPayments;
        protected global::System.Web.UI.WebControls.Image imgNavPayments;
        protected global::System.Web.UI.WebControls.Label lblTextPayments;
        protected global::System.Web.UI.WebControls.HyperLink lnkNavSettings;
        protected global::System.Web.UI.WebControls.Image imgNavSettings;
        protected global::System.Web.UI.WebControls.Label lblTextSettings;
        protected global::System.Web.UI.WebControls.Panel pnlSidebarBottom;
        protected global::System.Web.UI.WebControls.LinkButton btnNavLogout;
        protected global::System.Web.UI.WebControls.Image imgNavLogout;
        protected global::System.Web.UI.WebControls.Label lblTextLogout;
        protected global::System.Web.UI.WebControls.Panel pnlMainArea;
        protected global::System.Web.UI.WebControls.Panel pnlTopbar;
        protected global::System.Web.UI.WebControls.Panel pnlSearchWrapper;
        protected global::System.Web.UI.WebControls.Panel pnlSearchIcon;
        protected global::System.Web.UI.WebControls.Image imgSearchIcon;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Panel pnlProfileWidget;
        protected global::System.Web.UI.WebControls.Panel pnlAvatarCircle;
        protected global::System.Web.UI.WebControls.Image imgAdminAvatar;
        protected global::System.Web.UI.WebControls.Panel pnlProfileInfo;
        protected global::System.Web.UI.WebControls.Label lblAdminRole;
        protected global::System.Web.UI.WebControls.Label lblAdminName;
        protected global::System.Web.UI.WebControls.Panel pnlContentArea;
        protected global::System.Web.UI.WebControls.Label lblPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlStatsGrid;
        protected global::System.Web.UI.WebControls.Panel pnlStatUsers;
        protected global::System.Web.UI.WebControls.Label lblStatUsersTitle;
        protected global::System.Web.UI.WebControls.Label lblStatUsersValue;
        protected global::System.Web.UI.WebControls.Label lblStatUsersChange;
        protected global::System.Web.UI.WebControls.Panel pnlStatSalons;
        protected global::System.Web.UI.WebControls.Label lblStatSalonsTitle;
        protected global::System.Web.UI.WebControls.Label lblStatUsersValu2;
        protected global::System.Web.UI.WebControls.Label lblStatSalonsValue;
        protected global::System.Web.UI.WebControls.Label lblStatSalonsChange;
        protected global::System.Web.UI.WebControls.Panel pnlStatBookings;
        protected global::System.Web.UI.WebControls.Label lblStatBookingsTitle;
        protected global::System.Web.UI.WebControls.Label lblStatBookingsValue;
        protected global::System.Web.UI.WebControls.Label lblStatBookingsChange;
        protected global::System.Web.UI.WebControls.Panel pnlStatRevenue;
        protected global::System.Web.UI.WebControls.Label lblStatRevenueTitle;
        protected global::System.Web.UI.WebControls.Label lblStatRevenueValue;
        protected global::System.Web.UI.WebControls.Label lblStatRevenueChange;
        protected global::System.Web.UI.WebControls.Panel pnlStatsSecondaryGrid;
        protected global::System.Web.UI.WebControls.Panel pnlStatReviews;
        protected global::System.Web.UI.WebControls.Label lblStatReviewsTitle;
        protected global::System.Web.UI.WebControls.Label lblStatReviewsValue;
        protected global::System.Web.UI.WebControls.Label lblStatReviewsChange;
        protected global::System.Web.UI.WebControls.Panel pnlStatApprovals;
        protected global::System.Web.UI.WebControls.Label lblStatApprovalsTitle;
        protected global::System.Web.UI.WebControls.Label lblStatApprovalsValue;
        protected global::System.Web.UI.WebControls.Label lblStatApprovalsChange;
        protected global::System.Web.UI.WebControls.Label lblRecentBookingsHeading;
        protected global::System.Web.UI.WebControls.Panel pnlRecentBookingsCard;
        protected global::System.Web.UI.WebControls.Panel pnlBookingRow1;
        protected global::System.Web.UI.WebControls.Panel pnlAvatar1;
        protected global::System.Web.UI.WebControls.Image imgAvatar1;
        protected global::System.Web.UI.WebControls.Label lblBooking1Name;
        protected global::System.Web.UI.WebControls.Label lblBooking1Salon;
        protected global::System.Web.UI.WebControls.Label lblBooking1Date;
        protected global::System.Web.UI.WebControls.Panel pnlStatus1;
        protected global::System.Web.UI.WebControls.Panel pnlStatus1Badge;
        protected global::System.Web.UI.WebControls.Label lblStatus1Text;
        protected global::System.Web.UI.WebControls.Image imgStatus1Check;
        protected global::System.Web.UI.WebControls.Panel pnlBookingRow2;
        protected global::System.Web.UI.WebControls.Panel pnlAvatar2;
        protected global::System.Web.UI.WebControls.Image imgAvatar2;
        protected global::System.Web.UI.WebControls.Label lblBooking2Name;
        protected global::System.Web.UI.WebControls.Label lblBooking2Salon;
        protected global::System.Web.UI.WebControls.Label lblBooking2Date;
        protected global::System.Web.UI.WebControls.Panel pnlStatus2;
        protected global::System.Web.UI.WebControls.Panel pnlStatus2Badge;
        protected global::System.Web.UI.WebControls.Label lblStatus2Text;
        protected global::System.Web.UI.WebControls.Panel pnlBookingRow3;
        protected global::System.Web.UI.WebControls.Panel pnlAvatar3;
        protected global::System.Web.UI.WebControls.Image imgAvatar3;
        protected global::System.Web.UI.WebControls.Label lblBooking3Name;
        protected global::System.Web.UI.WebControls.Label lblBooking3Salon;
        protected global::System.Web.UI.WebControls.Label lblBooking3Date;
        protected global::System.Web.UI.WebControls.Panel pnlStatus3;
        protected global::System.Web.UI.WebControls.Panel pnlStatus3Badge;
        protected global::System.Web.UI.WebControls.Label lblStatus3Text;
        protected global::System.Web.UI.WebControls.Image imgStatus3Check;
    }
}
