//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class BookAppointment
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmBook;
        protected global::System.Web.UI.WebControls.Panel pnlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlLogoArea;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Panel pnlNav;
        protected global::System.Web.UI.WebControls.LinkButton lnkHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkSalon;
        protected global::System.Web.UI.WebControls.LinkButton lnkReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkAboutUs;

        protected global::System.Web.UI.WebControls.Panel pnlBookingMain;
        protected global::System.Web.UI.WebControls.Label lblPageTitle;

        protected global::System.Web.UI.WebControls.Panel pnlStepper;
        protected global::System.Web.UI.WebControls.Panel pnlStep1;
        protected global::System.Web.UI.WebControls.Label lblStep1Num;
        protected global::System.Web.UI.WebControls.Label lblStep1Text;
        protected global::System.Web.UI.WebControls.Panel pnlStepLine1;
        protected global::System.Web.UI.WebControls.Panel pnlStep2;
        protected global::System.Web.UI.WebControls.Label lblStep2Num;
        protected global::System.Web.UI.WebControls.Label lblStep2Text;
        protected global::System.Web.UI.WebControls.Panel pnlStepLine2;
        protected global::System.Web.UI.WebControls.Panel pnlStep3;
        protected global::System.Web.UI.WebControls.Label lblStep3Num;
        protected global::System.Web.UI.WebControls.Label lblStep3Text;

        protected global::System.Web.UI.WebControls.Panel pnlCardsContainer;

        protected global::System.Web.UI.WebControls.Panel pnlCardServices;
        protected global::System.Web.UI.WebControls.Label lblChooseServices;
        protected global::System.Web.UI.WebControls.Panel pnlDivider1;
        protected global::System.Web.UI.WebControls.Panel pnlServicesList;
        protected global::System.Web.UI.WebControls.Panel pnlService1;
        protected global::System.Web.UI.WebControls.Panel pnlServiceLeft1;
        protected global::System.Web.UI.WebControls.CheckBox chkHairCut;
        protected global::System.Web.UI.WebControls.Label lblPriceHairCut;
        protected global::System.Web.UI.WebControls.Panel pnlService2;
        protected global::System.Web.UI.WebControls.Panel pnlServiceLeft2;
        protected global::System.Web.UI.WebControls.CheckBox chkBeardTrim;
        protected global::System.Web.UI.WebControls.Label lblPriceBeardTrim;
        protected global::System.Web.UI.WebControls.Panel pnlService3;
        protected global::System.Web.UI.WebControls.Panel pnlServiceLeft3;
        protected global::System.Web.UI.WebControls.CheckBox chkHairColor;
        protected global::System.Web.UI.WebControls.Label lblPriceHairColor;
        protected global::System.Web.UI.WebControls.Panel pnlService4;
        protected global::System.Web.UI.WebControls.Panel pnlServiceLeft4;
        protected global::System.Web.UI.WebControls.CheckBox chkFacial;
        protected global::System.Web.UI.WebControls.Label lblPriceFacial;
        protected global::System.Web.UI.WebControls.Panel pnlService5;
        protected global::System.Web.UI.WebControls.Panel pnlServiceLeft5;
        protected global::System.Web.UI.WebControls.CheckBox chkHairSpa;
        protected global::System.Web.UI.WebControls.Label lblPriceHairSpa;

        protected global::System.Web.UI.WebControls.Panel pnlCardDate;
        protected global::System.Web.UI.WebControls.Label lblSelectDate;
        protected global::System.Web.UI.WebControls.Panel pnlDivider2;
        protected global::System.Web.UI.WebControls.Panel pnlCalHeader;
        protected global::System.Web.UI.WebControls.LinkButton btnCalPrev;
        protected global::System.Web.UI.WebControls.Panel pnlCalDropdowns;
        protected global::System.Web.UI.WebControls.DropDownList ddlCalMonth;
        protected global::System.Web.UI.WebControls.DropDownList ddlCalYear;
        protected global::System.Web.UI.WebControls.LinkButton btnCalNext;
        protected global::System.Web.UI.WebControls.Calendar calBooking;
        protected global::System.Web.UI.WebControls.Label lblSelectedDateDisplay;

        protected global::System.Web.UI.WebControls.Panel pnlCardTime;
        protected global::System.Web.UI.WebControls.Label lblSelectTime;
        protected global::System.Web.UI.WebControls.Panel pnlDivider3;
        protected global::System.Web.UI.WebControls.Panel pnlMorningGroup;
        protected global::System.Web.UI.WebControls.Label lblMorning;
        protected global::System.Web.UI.WebControls.Panel pnlMorningSlots;
        protected global::System.Web.UI.WebControls.LinkButton btnTime0900AM;
        protected global::System.Web.UI.WebControls.LinkButton btnTime1000AM;
        protected global::System.Web.UI.WebControls.LinkButton btnTime1100AM;
        protected global::System.Web.UI.WebControls.LinkButton btnTime1200PM;
        protected global::System.Web.UI.WebControls.Panel pnlAfternoonGroup;
        protected global::System.Web.UI.WebControls.Label lblAfternoon;
        protected global::System.Web.UI.WebControls.Panel pnlAfternoonSlots;
        protected global::System.Web.UI.WebControls.LinkButton btnTime0100PM;
        protected global::System.Web.UI.WebControls.LinkButton btnTime0200PM;
        protected global::System.Web.UI.WebControls.LinkButton btnTime0300PM;
        protected global::System.Web.UI.WebControls.LinkButton btnTime0400PM;
        protected global::System.Web.UI.WebControls.Panel pnlEveningGroup;
        protected global::System.Web.UI.WebControls.Label lblEvening;
        protected global::System.Web.UI.WebControls.Panel pnlEveningSlots;
        protected global::System.Web.UI.WebControls.LinkButton btnTime0500PM;
        protected global::System.Web.UI.WebControls.LinkButton btnTime0600PM;
        protected global::System.Web.UI.WebControls.LinkButton btnTime0700PM;
        protected global::System.Web.UI.WebControls.LinkButton btnTime0800PM;
        protected global::System.Web.UI.WebControls.Label lblSelectedTimeDisplay;

        protected global::System.Web.UI.WebControls.Panel pnlNextWrapper;
        protected global::System.Web.UI.WebControls.Button btnNext;
        protected global::System.Web.UI.WebControls.Panel pnlBookingFeedback;
        protected global::System.Web.UI.WebControls.Label lblFeedbackMessage;

        protected global::System.Web.UI.WebControls.Panel pnlFooter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterColumns;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBrandCol;
        protected global::System.Web.UI.WebControls.Panel pnlFooterLogoRow;
        protected global::System.Web.UI.WebControls.Image imgFooterLogo;
        protected global::System.Web.UI.WebControls.Label lblFooterBrand;
        protected global::System.Web.UI.WebControls.Label lblFooterTagline;
        protected global::System.Web.UI.WebControls.Panel pnlFooterQuickLinks;
        protected global::System.Web.UI.WebControls.Label lblQuickLinksTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterSalons;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterAboutUs;
        protected global::System.Web.UI.WebControls.Panel pnlFooterCustomer;
        protected global::System.Web.UI.WebControls.Label lblCustomerTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterMyBooking;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterContact;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSupport;
        protected global::System.Web.UI.WebControls.Label lblSupportTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHelp;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterTerms;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterPrivacy;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterCancellation;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSocial;
        protected global::System.Web.UI.WebControls.Label lblFollowUsTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSocialRow;
        protected global::System.Web.UI.WebControls.HyperLink hlFacebook;
        protected global::System.Web.UI.WebControls.HyperLink hlInstagram;
        protected global::System.Web.UI.WebControls.HyperLink hlTwitter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBottom;
        protected global::System.Web.UI.WebControls.Label lblCopyright;
    }
}
