//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class Default
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmMain;
        protected global::System.Web.UI.WebControls.Panel pnlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlLogoArea;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Panel pnlNav;
        protected global::System.Web.UI.WebControls.LinkButton lnkHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkSalon;
        protected global::System.Web.UI.WebControls.Panel pnlUserArea;
        protected global::System.Web.UI.WebControls.Image imgUserAvatar;
        protected global::System.Web.UI.WebControls.LinkButton lnkUserToggle;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.Panel pnlUserDropdown;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuAboutUs;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuMyProfile;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuSetting;

        protected global::System.Web.UI.WebControls.Panel pnlHeroWrapper;
        protected global::System.Web.UI.WebControls.Panel pnlHero;
        protected global::System.Web.UI.WebControls.Image imgHeroBg;
        protected global::System.Web.UI.WebControls.Panel pnlHeroOverlay;
        protected global::System.Web.UI.WebControls.Panel pnlHeroText;
        protected global::System.Web.UI.WebControls.Label lblHeroTitle;
        protected global::System.Web.UI.WebControls.Label lblHeroTagline;
        protected global::System.Web.UI.WebControls.Label lblHeroSubtitle;
        protected global::System.Web.UI.WebControls.Button btnBookAppointment;

        protected global::System.Web.UI.WebControls.Panel pnlSearchCardWrapper;
        protected global::System.Web.UI.WebControls.Panel pnlSearchCard;
        protected global::System.Web.UI.WebControls.Label lblSearchTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSearchFields;
        protected global::System.Web.UI.WebControls.Panel pnlLocationField;
        protected global::System.Web.UI.WebControls.Label lblLocation;
        protected global::System.Web.UI.WebControls.DropDownList ddlLocation;
        protected global::System.Web.UI.WebControls.Panel pnlServiceField;
        protected global::System.Web.UI.WebControls.Label lblServiceField;
        protected global::System.Web.UI.WebControls.DropDownList ddlService;
        protected global::System.Web.UI.WebControls.Panel pnlDateField;
        protected global::System.Web.UI.WebControls.Label lblDateField;
        protected global::System.Web.UI.WebControls.DropDownList ddlDate;
        protected global::System.Web.UI.WebControls.Button btnSearch;

        protected global::System.Web.UI.WebControls.Panel pnlSalonsSection;
        protected global::System.Web.UI.WebControls.Panel pnlSalonsHeaderRow;
        protected global::System.Web.UI.WebControls.Label lblSalonsTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSalonGrid;
        protected global::System.Web.UI.WebControls.Repeater rptSalons;

        protected global::System.Web.UI.WebControls.Panel pnlServicesSection;
        protected global::System.Web.UI.WebControls.Panel pnlServicesHeaderRow;
        protected global::System.Web.UI.WebControls.Label lblServicesTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkServicesViewAll;
        protected global::System.Web.UI.WebControls.Panel pnlServiceGrid;
        protected global::System.Web.UI.WebControls.Repeater rptServices;

        protected global::System.Web.UI.WebControls.Panel pnlReviewsSection;
        protected global::System.Web.UI.WebControls.Panel pnlReviewsHeaderRow;
        protected global::System.Web.UI.WebControls.Label lblReviewsTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkReviewsViewAll;
        protected global::System.Web.UI.WebControls.Panel pnlReviewRow;
        protected global::System.Web.UI.WebControls.LinkButton lnkReviewPrev;
        protected global::System.Web.UI.WebControls.Panel pnlReviewGrid;
        protected global::System.Web.UI.WebControls.Repeater rptReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkReviewNext;

        protected global::System.Web.UI.WebControls.Panel pnlFooter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterColumns;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBrandCol;
        protected global::System.Web.UI.WebControls.Panel pnlFooterLogoRow;
        protected global::System.Web.UI.WebControls.Image imgFooterLogo;
        protected global::System.Web.UI.WebControls.Label lblFooterTagline;
        protected global::System.Web.UI.WebControls.Panel pnlFooterQuickLinks;
        protected global::System.Web.UI.WebControls.Label lblQuickLinksTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterSalons;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterAboutUs;
        protected global::System.Web.UI.WebControls.Panel pnlFooterCustomer;
        protected global::System.Web.UI.WebControls.Label lblCustomerTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterMyBooking;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterContact;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSupport;
        protected global::System.Web.UI.WebControls.Label lblSupportTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHelpCenter;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterPrivacy;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterCancellation;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSocial;
        protected global::System.Web.UI.WebControls.Label lblFollowUsTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSocialRow;
        protected global::System.Web.UI.WebControls.HyperLink hlFacebook;
        protected global::System.Web.UI.WebControls.HyperLink hlInstagram;
        protected global::System.Web.UI.WebControls.HyperLink hlTwitter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBottom;
        protected global::System.Web.UI.WebControls.Label lblCopyright;
    }
}
