//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class ForgotPassword
    {
        // User control header
        protected global::Stylio_Salon.SiteHeader ctrlHeader;

        // Auth card wrapper
        protected global::System.Web.UI.WebControls.Panel pnlAuthBody;
        protected global::System.Web.UI.WebControls.Panel pnlAuthCard;
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.ValidationSummary valSummary;

        // Email group
        protected global::System.Web.UI.WebControls.Panel pnlEmailGroup;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        // New password group
        protected global::System.Web.UI.WebControls.Panel pnlNewPasswordGroup;
        protected global::System.Web.UI.WebControls.Label lblNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNewPassword;

        // Confirm password group
        protected global::System.Web.UI.WebControls.Panel pnlConfirmPasswordGroup;
        protected global::System.Web.UI.WebControls.Label lblConfirmPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvConfirmPassword;
        protected global::System.Web.UI.WebControls.CompareValidator cvConfirmPassword;

        // Buttons & links
        protected global::System.Web.UI.WebControls.Button btnResetPassword;
        protected global::System.Web.UI.WebControls.Panel pnlLoginRow;
        protected global::System.Web.UI.WebControls.Label lblRememberPassword;
        protected global::System.Web.UI.WebControls.LinkButton lnkBackToLogin;
    }
}
