//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{


    public partial class Login
    {
        protected global::Stylio_Salon.SiteHeader ctrlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlAuthBody;
        protected global::System.Web.UI.WebControls.Panel pnlAuthCard;
        protected global::System.Web.UI.WebControls.Label lblTitle;
        protected global::System.Web.UI.WebControls.ValidationSummary valSummary;
        protected global::System.Web.UI.WebControls.Panel pnlEmailGroup;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.Panel pnlPasswordGroup;
        protected global::System.Web.UI.WebControls.Label lblPassword;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;
        protected global::System.Web.UI.WebControls.Panel pnlForgotRow;
        protected global::System.Web.UI.WebControls.LinkButton lnkForgotPassword;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.WebControls.Panel pnlRegisterRow;
        protected global::System.Web.UI.WebControls.Label lblNoAccount;
        protected global::System.Web.UI.WebControls.LinkButton lnkRegister;
    }
}
