//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class MyBooking
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmMyBooking;
        protected global::System.Web.UI.WebControls.Panel pnlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlLogoArea;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Panel pnlNav;
        protected global::System.Web.UI.WebControls.LinkButton lnkHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkSalon;
        protected global::System.Web.UI.WebControls.LinkButton lnkReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkAboutUs;

        protected global::System.Web.UI.WebControls.Panel pnlBookingPage;
        protected global::System.Web.UI.WebControls.Label lblPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlTabsBar;
        protected global::System.Web.UI.WebControls.LinkButton btnTabUpcoming;
        protected global::System.Web.UI.WebControls.LinkButton btnTabPast;
        protected global::System.Web.UI.WebControls.Label lblStatusMessage;

        protected global::System.Web.UI.WebControls.Panel pnlUpcomingContent;
        protected global::System.Web.UI.WebControls.Panel pnlUpCard1;
        protected global::System.Web.UI.WebControls.Image imgUp1;
        protected global::System.Web.UI.WebControls.Panel pnlUpBody1;
        protected global::System.Web.UI.WebControls.Panel pnlUpHeader1;
        protected global::System.Web.UI.WebControls.Label lblUpTitle1;
        protected global::System.Web.UI.WebControls.Label lblUpBadge1;
        protected global::System.Web.UI.WebControls.Label lblUpStylist1;
        protected global::System.Web.UI.WebControls.Label lblUpSalon1;
        protected global::System.Web.UI.WebControls.Label lblUpDateTime1;
        protected global::System.Web.UI.WebControls.Panel pnlUpAction1;
        protected global::System.Web.UI.WebControls.LinkButton btnCancel1;

        protected global::System.Web.UI.WebControls.Panel pnlUpCard2;
        protected global::System.Web.UI.WebControls.Image imgUp2;
        protected global::System.Web.UI.WebControls.Panel pnlUpBody2;
        protected global::System.Web.UI.WebControls.Panel pnlUpHeader2;
        protected global::System.Web.UI.WebControls.Label lblUpTitle2;
        protected global::System.Web.UI.WebControls.Label lblUpBadge2;
        protected global::System.Web.UI.WebControls.Label lblUpStylist2;
        protected global::System.Web.UI.WebControls.Label lblUpSalon2;
        protected global::System.Web.UI.WebControls.Label lblUpDateTime2;
        protected global::System.Web.UI.WebControls.Panel pnlUpAction2;
        protected global::System.Web.UI.WebControls.LinkButton btnCancel2;

        protected global::System.Web.UI.WebControls.Panel pnlPastContent;
        protected global::System.Web.UI.WebControls.Panel pnlPastCard1;
        protected global::System.Web.UI.WebControls.Image imgPast1;
        protected global::System.Web.UI.WebControls.Panel pnlPastBody1;
        protected global::System.Web.UI.WebControls.Panel pnlPastHeader1;
        protected global::System.Web.UI.WebControls.Label lblPastTitle1;
        protected global::System.Web.UI.WebControls.Label lblPastBadge1;
        protected global::System.Web.UI.WebControls.Label lblPastStylist1;
        protected global::System.Web.UI.WebControls.Label lblPastSalon1;
        protected global::System.Web.UI.WebControls.Label lblPastDateTime1;

        protected global::System.Web.UI.WebControls.Panel pnlPastCard2;
        protected global::System.Web.UI.WebControls.Image imgPast2;
        protected global::System.Web.UI.WebControls.Panel pnlPastBody2;
        protected global::System.Web.UI.WebControls.Panel pnlPastHeader2;
        protected global::System.Web.UI.WebControls.Label lblPastTitle2;
        protected global::System.Web.UI.WebControls.Label lblPastBadge2;
        protected global::System.Web.UI.WebControls.Label lblPastStylist2;
        protected global::System.Web.UI.WebControls.Label lblPastSalon2;
        protected global::System.Web.UI.WebControls.Label lblPastDateTime2;

        protected global::System.Web.UI.WebControls.Panel pnlFooter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterColumns;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBrandCol;
        protected global::System.Web.UI.WebControls.Panel pnlFooterLogoRow;
        protected global::System.Web.UI.WebControls.Image imgFooterLogo;
        protected global::System.Web.UI.WebControls.Label lblFooterBrand;
        protected global::System.Web.UI.WebControls.Label lblFooterTagline;
        protected global::System.Web.UI.WebControls.Panel pnlFooterQuickLinks;
        protected global::System.Web.UI.WebControls.Label lblQuickLinksTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterSalons;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterAboutUs;
        protected global::System.Web.UI.WebControls.Panel pnlFooterCustomer;
        protected global::System.Web.UI.WebControls.Label lblCustomerTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterMyBooking;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterContact;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSupport;
        protected global::System.Web.UI.WebControls.Label lblSupportTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHelp;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterTerms;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterPrivacy;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterCancellation;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSocial;
        protected global::System.Web.UI.WebControls.Label lblFollowUsTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSocialRow;
        protected global::System.Web.UI.WebControls.HyperLink hlFacebook;
        protected global::System.Web.UI.WebControls.HyperLink hlInstagram;
        protected global::System.Web.UI.WebControls.HyperLink hlTwitter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBottom;
        protected global::System.Web.UI.WebControls.Label lblCopyright;
    }
}
