//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class MyProfile
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmMyProfile;
        protected global::System.Web.UI.WebControls.Panel pnlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlLogoArea;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Panel pnlNav;
        protected global::System.Web.UI.WebControls.LinkButton lnkHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkSalon;

        protected global::System.Web.UI.WebControls.Panel pnlAccountPage;
        protected global::System.Web.UI.WebControls.Label lblPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlContentWrapper;

        protected global::System.Web.UI.WebControls.Panel pnlSidebar;
        protected global::System.Web.UI.WebControls.LinkButton lnkSideProfile;
        protected global::System.Web.UI.WebControls.Label lblIconProfile;
        protected global::System.Web.UI.WebControls.Label lblTextProfile;
        protected global::System.Web.UI.WebControls.LinkButton lnkSideBooking;
        protected global::System.Web.UI.WebControls.Label lblIconBooking;
        protected global::System.Web.UI.WebControls.Label lblTextBooking;
        protected global::System.Web.UI.WebControls.LinkButton lnkSidePayment;
        protected global::System.Web.UI.WebControls.Label lblIconPayment;
        protected global::System.Web.UI.WebControls.Label lblTextPayment;
        protected global::System.Web.UI.WebControls.LinkButton lnkSideLogout;
        protected global::System.Web.UI.WebControls.Label lblIconLogout;
        protected global::System.Web.UI.WebControls.Label lblTextLogout;

        protected global::System.Web.UI.WebControls.Panel pnlProfileCard;
        protected global::System.Web.UI.WebControls.Panel pnlAvatarWrapper;
        protected global::System.Web.UI.WebControls.Panel pnlAvatarCircle;
        protected global::System.Web.UI.WebControls.Label lblAvatarIcon;
        protected global::System.Web.UI.WebControls.Label lblProfileName;
        protected global::System.Web.UI.WebControls.Panel pnlProfileInfoGroup;
        protected global::System.Web.UI.WebControls.Panel pnlEmailRow;
        protected global::System.Web.UI.WebControls.Label lblEmailIcon;
        protected global::System.Web.UI.WebControls.Label lblProfileEmail;
        protected global::System.Web.UI.WebControls.Panel pnlPhoneRow;
        protected global::System.Web.UI.WebControls.Label lblPhoneIcon;
        protected global::System.Web.UI.WebControls.Label lblProfilePhone;

        protected global::System.Web.UI.WebControls.Panel pnlFooter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterColumns;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBrandCol;
        protected global::System.Web.UI.WebControls.Panel pnlFooterLogoRow;
        protected global::System.Web.UI.WebControls.Image imgFooterLogo;
        protected global::System.Web.UI.WebControls.Label lblFooterBrand;
        protected global::System.Web.UI.WebControls.Label lblFooterTagline;
        protected global::System.Web.UI.WebControls.Panel pnlFooterQuickLinks;
        protected global::System.Web.UI.WebControls.Label lblQuickLinksTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterSalons;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterAboutUs;
        protected global::System.Web.UI.WebControls.Panel pnlFooterCustomer;
        protected global::System.Web.UI.WebControls.Label lblCustomerTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterMyBooking;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterContact;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSupport;
        protected global::System.Web.UI.WebControls.Label lblSupportTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHelp;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterPrivacy;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterCancellation;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSocial;
        protected global::System.Web.UI.WebControls.Label lblFollowUsTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSocialRow;
        protected global::System.Web.UI.WebControls.HyperLink hlFacebook;
        protected global::System.Web.UI.WebControls.HyperLink hlInstagram;
        protected global::System.Web.UI.WebControls.HyperLink hlTwitter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBottom;
        protected global::System.Web.UI.WebControls.Label lblCopyright;
    }
}
