//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class MyProfile
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmMyProfile;
        protected global::System.Web.UI.WebControls.Panel pnlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlLogoArea;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Panel pnlNav;
        protected global::System.Web.UI.WebControls.LinkButton lnkHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkSalon;
        protected global::System.Web.UI.WebControls.Panel pnlUserArea;
        protected global::System.Web.UI.WebControls.Image imgUserAvatar;
        protected global::System.Web.UI.WebControls.LinkButton lnkUserToggle;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.Panel pnlUserDropdown;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuAboutUs;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuMyProfile;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuSetting;

        protected global::System.Web.UI.WebControls.Panel pnlPageBody;
        protected global::System.Web.UI.WebControls.Panel pnlProfileCard;
        protected global::System.Web.UI.WebControls.Label lblPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlFullName;
        protected global::System.Web.UI.WebControls.Label lblFullName;
        protected global::System.Web.UI.WebControls.TextBox txtFullName;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFullName;
        protected global::System.Web.UI.WebControls.Panel pnlEmail;
        protected global::System.Web.UI.WebControls.Label lblEmail;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;
        protected global::System.Web.UI.WebControls.Panel pnlMobile;
        protected global::System.Web.UI.WebControls.Label lblMobile;
        protected global::System.Web.UI.WebControls.TextBox txtMobile;
        protected global::System.Web.UI.WebControls.Button btnSaveProfile;
        protected global::System.Web.UI.WebControls.Panel pnlBackRow;
        protected global::System.Web.UI.WebControls.LinkButton lnkBackHome;

        protected global::System.Web.UI.WebControls.Panel pnlFooter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBottom;
        protected global::System.Web.UI.WebControls.Label lblCopyright;
    }
}
