//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class Payment
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmPayment;
        protected global::System.Web.UI.WebControls.Panel pnlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlLogoArea;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Panel pnlNav;
        protected global::System.Web.UI.WebControls.LinkButton lnkHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkSalon;
        protected global::System.Web.UI.WebControls.LinkButton lnkReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkAboutUs;

        protected global::System.Web.UI.WebControls.Panel pnlPaymentPage;
        protected global::System.Web.UI.WebControls.Label lblPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlContentWrapper;

        protected global::System.Web.UI.WebControls.Panel pnlSummaryCard;
        protected global::System.Web.UI.WebControls.Label lblSummaryTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSummaryDivider1;
        protected global::System.Web.UI.WebControls.Label lblSalonName;
        protected global::System.Web.UI.WebControls.Label lblBookingDateTime;
        protected global::System.Web.UI.WebControls.Panel pnlItemsList;
        protected global::System.Web.UI.WebControls.Repeater rptSummaryItems;
        protected global::System.Web.UI.WebControls.Panel pnlTaxRow;
        protected global::System.Web.UI.WebControls.Label lblTaxLabel;
        protected global::System.Web.UI.WebControls.Label lblTaxPrice;
        protected global::System.Web.UI.WebControls.Panel pnlTotalDivider;
        protected global::System.Web.UI.WebControls.Panel pnlTotalRow;
        protected global::System.Web.UI.WebControls.Label lblTotalLabel;
        protected global::System.Web.UI.WebControls.Label lblTotalPrice;

        protected global::System.Web.UI.WebControls.Panel pnlPaymentMethodCol;
        protected global::System.Web.UI.WebControls.Label lblPaymentMethodTitle;
        protected global::System.Web.UI.WebControls.Panel pnlPaymentCard;
        protected global::System.Web.UI.WebControls.Panel pnlCashOptionBox;
        protected global::System.Web.UI.WebControls.Panel pnlOptionLeft;
        protected global::System.Web.UI.WebControls.Label lblWalletIcon;
        protected global::System.Web.UI.WebControls.Panel pnlOptionTexts;
        protected global::System.Web.UI.WebControls.Label lblOptionTitle;
        protected global::System.Web.UI.WebControls.Label lblOptionDesc;
        protected global::System.Web.UI.WebControls.Panel pnlOptionRadio;
        protected global::System.Web.UI.WebControls.RadioButton rbCashPayment;

        protected global::System.Web.UI.WebControls.Panel pnlActionArea;
        protected global::System.Web.UI.WebControls.Button btnPayNow;
        protected global::System.Web.UI.WebControls.Label lblSecureNotice;
        protected global::System.Web.UI.WebControls.Panel pnlSuccessBox;
        protected global::System.Web.UI.WebControls.Label lblSuccessTitle;
        protected global::System.Web.UI.WebControls.Label lblSuccessDesc;

        protected global::System.Web.UI.WebControls.Panel pnlFooter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterColumns;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBrandCol;
        protected global::System.Web.UI.WebControls.Panel pnlFooterLogoRow;
        protected global::System.Web.UI.WebControls.Image imgFooterLogo;
        protected global::System.Web.UI.WebControls.Label lblFooterBrand;
        protected global::System.Web.UI.WebControls.Label lblFooterTagline;
        protected global::System.Web.UI.WebControls.Panel pnlFooterQuickLinks;
        protected global::System.Web.UI.WebControls.Label lblQuickLinksTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterSalons;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterAboutUs;
        protected global::System.Web.UI.WebControls.Panel pnlFooterCustomer;
        protected global::System.Web.UI.WebControls.Label lblCustomerTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterMyBooking;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterContact;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSupport;
        protected global::System.Web.UI.WebControls.Label lblSupportTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHelp;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterTerms;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterPrivacy;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterCancellation;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSocial;
        protected global::System.Web.UI.WebControls.Label lblFollowUsTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSocialRow;
        protected global::System.Web.UI.WebControls.HyperLink hlFacebook;
        protected global::System.Web.UI.WebControls.HyperLink hlInstagram;
        protected global::System.Web.UI.WebControls.HyperLink hlTwitter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBottom;
        protected global::System.Web.UI.WebControls.Label lblCopyright;
    }
}
