//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class Settings
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmSettings;
        protected global::System.Web.UI.WebControls.Panel pnlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlLogoArea;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Panel pnlNav;
        protected global::System.Web.UI.WebControls.LinkButton lnkHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkSalon;

        protected global::System.Web.UI.WebControls.Panel pnlAccountPage;
        protected global::System.Web.UI.WebControls.Label lblPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlContentWrapper;

        protected global::System.Web.UI.WebControls.Panel pnlSidebar;
        protected global::System.Web.UI.WebControls.LinkButton lnkSideProfile;
        protected global::System.Web.UI.WebControls.Label lblIconProfile;
        protected global::System.Web.UI.WebControls.Label lblTextProfile;
        protected global::System.Web.UI.WebControls.LinkButton lnkSideBooking;
        protected global::System.Web.UI.WebControls.Label lblIconBooking;
        protected global::System.Web.UI.WebControls.Label lblTextBooking;
        protected global::System.Web.UI.WebControls.LinkButton lnkSideSettings;
        protected global::System.Web.UI.WebControls.Label lblIconSettings;
        protected global::System.Web.UI.WebControls.Label lblTextSettings;
        protected global::System.Web.UI.WebControls.LinkButton lnkSidePayment;
        protected global::System.Web.UI.WebControls.Label lblIconPayment;
        protected global::System.Web.UI.WebControls.Label lblTextPayment;
        protected global::System.Web.UI.WebControls.LinkButton lnkSideLogout;
        protected global::System.Web.UI.WebControls.Label lblIconLogout;
        protected global::System.Web.UI.WebControls.Label lblTextLogout;

        protected global::System.Web.UI.WebControls.Panel pnlSettingsCard;
        protected global::System.Web.UI.WebControls.Label lblSettingsCardTitle;
        protected global::System.Web.UI.WebControls.Panel pnlOptionsList;

        protected global::System.Web.UI.WebControls.LinkButton lnkOptionChangePassword;
        protected global::System.Web.UI.WebControls.Panel pnlPwdLeft;
        protected global::System.Web.UI.WebControls.Label lblLockIcon;
        protected global::System.Web.UI.WebControls.Label lblChangePasswordText;
        protected global::System.Web.UI.WebControls.Label lblChevron1;
        protected global::System.Web.UI.WebControls.Panel pnlDivider1;

        protected global::System.Web.UI.WebControls.LinkButton lnkOptionTerms;
        protected global::System.Web.UI.WebControls.Panel pnlTermsLeft;
        protected global::System.Web.UI.WebControls.Label lblDocIcon;
        protected global::System.Web.UI.WebControls.Label lblTermsText;
        protected global::System.Web.UI.WebControls.Label lblChevron2;
        protected global::System.Web.UI.WebControls.Panel pnlDivider2;

        protected global::System.Web.UI.WebControls.Panel pnlChangePasswordSub;
        protected global::System.Web.UI.WebControls.Label lblSubTitle;
        protected global::System.Web.UI.WebControls.Panel pnlCurrentPwdGroup;
        protected global::System.Web.UI.WebControls.Label lblCurrentPwd;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected global::System.Web.UI.WebControls.Panel pnlNewPwdGroup;
        protected global::System.Web.UI.WebControls.Label lblNewPwd;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.Panel pnlConfirmPwdGroup;
        protected global::System.Web.UI.WebControls.Label lblConfirmPwd;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnSavePassword;
        protected global::System.Web.UI.WebControls.Panel pnlStatusMsg;
        protected global::System.Web.UI.WebControls.Label lblStatusMessage;

        protected global::System.Web.UI.WebControls.Panel pnlFooter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterColumns;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBrandCol;
        protected global::System.Web.UI.WebControls.Panel pnlFooterLogoRow;
        protected global::System.Web.UI.WebControls.Image imgFooterLogo;
        protected global::System.Web.UI.WebControls.Label lblFooterBrand;
        protected global::System.Web.UI.WebControls.Label lblFooterTagline;
        protected global::System.Web.UI.WebControls.Panel pnlFooterQuickLinks;
        protected global::System.Web.UI.WebControls.Label lblQuickLinksTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterSalons;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterAboutUs;
        protected global::System.Web.UI.WebControls.Panel pnlFooterCustomer;
        protected global::System.Web.UI.WebControls.Label lblCustomerTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterMyBooking;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterContact;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSupport;
        protected global::System.Web.UI.WebControls.Label lblSupportTitle;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterHelp;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterTerms;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterPrivacy;
        protected global::System.Web.UI.WebControls.LinkButton lnkFooterCancellation;
        protected global::System.Web.UI.WebControls.Panel pnlFooterSocial;
        protected global::System.Web.UI.WebControls.Label lblFollowUsTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSocialRow;
        protected global::System.Web.UI.WebControls.HyperLink hlFacebook;
        protected global::System.Web.UI.WebControls.HyperLink hlInstagram;
        protected global::System.Web.UI.WebControls.HyperLink hlTwitter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBottom;
        protected global::System.Web.UI.WebControls.Label lblCopyright;
    }
}
