//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stylio_Salon
{
    public partial class Settings
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm frmSettings;
        protected global::System.Web.UI.WebControls.Panel pnlHeader;
        protected global::System.Web.UI.WebControls.Panel pnlLogoArea;
        protected global::System.Web.UI.WebControls.Image imgLogo;
        protected global::System.Web.UI.WebControls.Panel pnlNav;
        protected global::System.Web.UI.WebControls.LinkButton lnkHome;
        protected global::System.Web.UI.WebControls.LinkButton lnkServices;
        protected global::System.Web.UI.WebControls.LinkButton lnkSalon;
        protected global::System.Web.UI.WebControls.Panel pnlUserArea;
        protected global::System.Web.UI.WebControls.Image imgUserAvatar;
        protected global::System.Web.UI.WebControls.LinkButton lnkUserToggle;
        protected global::System.Web.UI.WebControls.Label lblUserName;
        protected global::System.Web.UI.WebControls.Panel pnlUserDropdown;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuReviews;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuAboutUs;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuMyProfile;
        protected global::System.Web.UI.WebControls.LinkButton lnkMenuSetting;

        protected global::System.Web.UI.WebControls.Panel pnlPageBody;
        protected global::System.Web.UI.WebControls.Panel pnlSettingsCard;
        protected global::System.Web.UI.WebControls.Label lblPageTitle;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Label lblSuccess;
        protected global::System.Web.UI.WebControls.Panel pnlCurrentPassword;
        protected global::System.Web.UI.WebControls.Label lblCurrentPassword;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentPassword;
        protected global::System.Web.UI.WebControls.Panel pnlNewPassword;
        protected global::System.Web.UI.WebControls.Label lblNewPassword;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revNewPassword;
        protected global::System.Web.UI.WebControls.Panel pnlConfirmPassword;
        protected global::System.Web.UI.WebControls.Label lblConfirmPassword;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.CompareValidator cvConfirmPassword;
        protected global::System.Web.UI.WebControls.Panel pnlNotifications;
        protected global::System.Web.UI.WebControls.Label lblNotifications;
        protected global::System.Web.UI.WebControls.CheckBox chkEmailNotifications;
        protected global::System.Web.UI.WebControls.Button btnSaveSettings;
        protected global::System.Web.UI.WebControls.Panel pnlLogoutRow;
        protected global::System.Web.UI.WebControls.LinkButton lnkLogout;

        protected global::System.Web.UI.WebControls.Panel pnlFooter;
        protected global::System.Web.UI.WebControls.Panel pnlFooterBottom;
        protected global::System.Web.UI.WebControls.Label lblCopyright;
    }
}
